name: Pint

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: use token
        run: echo "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl, zip, pcntl, bcmath, gd, pdo_mysql, exif, redis, imagick, soap, xsl, gmp, opcache, sockets, memcached, apcu, mongodb, swoole, xdebug
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ansi

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.php
          separator: " "
          base_sha: 'main'

      - name: Remove 'scripts/' from paths
        id: remove-scripts-path
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          modified_files=$(echo "$changed_files" | sed 's|scripts/||g')
          echo "Modified PHP files: $modified_files"
          echo "::set-output name=modified_files::$modified_files"

      - name: Check if PHP files have changed
        id: check-changed
        run: |
          if [ -z "${{ steps.remove-scripts-path.outputs.modified_files }}" ]; then
            echo "No PHP files have changed"
            echo "::set-output name=skip::true"
          else
            echo "Changed PHP files: ${{ steps.remove-scripts-path.outputs.modified_files }}"
            echo "::set-output name=skip::false"
          fi

      - name: Run pint for Changed Files
        if: ${{ steps.check-changed.outputs.skip == 'false' }}
        run: vendor/bin/pint -v ${{ steps.remove-scripts-path.outputs.modified_files }}
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update:Pintによる自動コミット
